### ISSUE TITLE
Android - wallet removal

### ISSUE THREAD

**Issue by galperins4** [ArkEcosystem/mobile-wallet#1]
Wallet removal doesn't appear to be working correctly. After removing  a wallet from a profile and confirming the removal it will reappear under the wallets for the profile.

**Comment by zillionn** [comment]
Same issue on Android 5.1.

**Comment by zillionn** [comment]
Well, after creating and deleting few addresses I was able to remove all the addresses.

**Comment by luciorubeens** [comment]
Will handle this in #174
