### ISSUE TITLE
Import Passphrase doesn't overwrite watch-only

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/mobile-wallet#12]
Importing watch only first, then importing a passphrase doesn't overwrite watch-only wallet

**Comment by yzheng710** [comment]
You can delete the watch-only wallet. Closed the app (actually close the app in the system memory) and restart the app and import the pass phrase

**Comment by alexbarnsley** [comment]
I know. I designed it (or thought I had) so that importing a passphrase would overwrite a watch-only

**Comment by boldninja** [comment]
![knownothing](https://user-images.githubusercontent.com/25795454/34393549-9518dd9c-eb53-11e7-8b7d-b0abee7f5d11.jpg)

**Comment by alexbarnsley** [comment]
:joy:

**Comment by alexbarnsley** [comment]
I wonder if this is related to #1. It may not be updating the storage properly
