### ISSUE TITLE
Feature - Passphrase word suggestion

### ISSUE THREAD

**Issue by air1one** [ArkEcosystem/mobile-wallet#126]
Hi, here is a suggestion I'd like to implement on the "import with passphrase" screen.

Basically, suggesting words as the user types, from the bip39 wordlist (and if he has not enabled the "custom (non BIP39) passphrase" toggle).
An example to make it clear : 
![138 197 79 32_8100_ pixel 2 2](https://user-images.githubusercontent.com/36802613/37915048-a7bf83ee-3129-11e8-8bc1-652bfd07cb62.png)

So the user start typing "sm" and then he starts to see suggested words from the wordlist, and as he keeps typing the suggestions become more precise.
It helps entering the passphrase and also helps avoiding mistakes.

I'd like your opinion on this before starting : do you like it, any thoughts on implementation / design ? @alexbarnsley 

Things I'm thinking about : 
- Suggested words design : 3 rounded buttons below the passphrase input ?
- Wordlists in different languages : suggest in the configured language ? But most of the time the words would be in english anyway (suggest configured language + english for the 1st word, then for the 11 words left we know which language it is ?)
- Start to suggest from 2 letters ?

Thanks.

**Comment by alexbarnsley** [comment]
@air1one sounds like a good idea! I have passed it to our design guy, Oleg, to see what he thinks and whether he has any tweaks on the designs to match the mobile app. I'll keep you posted! the functionality side sounds good I think unless someone else has something to add 👍

**Comment by air1one** [comment]
Thanks, so I'm starting on it 👍
