### ISSUE TITLE
Option to add custom networks

### ISSUE THREAD

**Issue by Nasicus** [ArkEcosystem/mobile-wallet#138]
What do you think about the option to add a custom network.

My general idea is doing something like this:

![image](https://user-images.githubusercontent.com/1086065/38323340-41668faa-383d-11e8-9b9b-892bb7efeb17.png)

Once you click "Custom" it will show you a form to add fields, if you already have added a custom network once, you will be able to choose it from a secon drop down (want to keep the first choice short & easy).

**Comment by Nasicus** [comment]
Nice - on it then :)

**Comment by luciorubeens** [comment]
Closed via #145
