### ISSUE TITLE
Enable OS notifications for transactions

### ISSUE THREAD

**Issue by wownmedia** [ArkEcosystem/mobile-wallet#165]
Discussed with @Air1 in slack, it would be nice to have the option to optionally monitor an address for new transactions and have the wallet send an OS notification. Maybe check every x time as a background task so it is balanced between 'live' and resource usage

**Comment by sleepdefic1t** [comment]
Notifications may require an extra notification service or server.

There is no mechanism in iOS—for example—to run code in the background and trigger notifications based on external(off-device) changes.

v2 and it’s state machine could solve half of the ‘Remote Notification’ issue though.

**Comment by luciorubeens** [comment]
Closed via #140
