### ISSUE TITLE
Converting Watch-only to Full wallet from QR without passphrase shows as a Full wallet

### ISSUE THREAD

**Issue by scottfree98227** [ArkEcosystem/mobile-wallet#167]
How do I switch and keep my Apple mobile wallet from a "watch only" to a "full" wallet?  When I touch "convert to full wallet" and scan the QR code on my desk top, it works but won't stay for the next time I open the app. I'm using version 1.0.0.  Why am I having to reenter this every time I open the app?  It always reverts back to a "watch only".

Thanks in advance!

**Comment by alexbarnsley** [comment]
@scottfree98227 you mentioned you're using version 1.0.0. Please could you try updating to version 1.1.0 to see if you're still experiencing the issue and come back to us. Thanks!

**Comment by scottfree98227** [comment]
I have tried.  I have deleted it from my phone, gone to ARK.io and downloaded the newer version by it just reverts back to the old version for whatever reason...

**Comment by alexbarnsley** [comment]
Ah the settings screen might still show v1.0.0. Can you see from the iPhone device settings what version is installed? I will have a test for it my end

**Comment by scottfree98227** [comment]
Well, it's still not working...  I guess I'll just live with it.

**Comment by alexbarnsley** [comment]
No need to live with it. I'll test on that version, but also the most recent codebase. We are due to release an updated mobile app version soon so it could have been resolved.

**Comment by scottfree98227** [comment]
Yes, I had also been manually entering my passphrase.  It wound switch to a full wallet but only while the app was open.  If I closed it and them re-opened it, it would go back to the watch only.  

I started fresh last night by re-entering the passphrase and this morning it's so far, so good.  I've closed it several times and re-opened several times.  It now seems to be retaining the full wallet.  Whatever bug it was, it seems to have fixed itself, at least for the time being.

Thanks much for the info and help.

Cheers!

**Comment by alexbarnsley** [comment]
@scottfree98227 not a problem. I do however think there is a bug. I don't believe the wallet was ever converted to a "full wallet". I think the bug is that it's showing you that it is, when it actually isn't. That's why it's changing back when you re-open the app. I'll reword this issue but i still need to confirm my theory. Thanks 👍
