### ISSUE TITLE
Alert when importing a brand new wallet

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/mobile-wallet#20]
>I think users should be alerted if the passphrase they entered does not import an existing wallet address, as opposed to having a new wallet generated by default if a passphrase is incorrect. Have seen quite a few confused users because of the lack of error prevention in this process.

Pulled from #10 by @erbogart28

**Comment by Hiram-Silvey** [comment]
Just tried this and I agree it needs a notification. After clicking the "import" button it generated a new wallet instead of alerting me that no wallet could be imported. I will try to check this out later today if I can, but no promises as this is my first time diving into the code :)

**Comment by DukeCounter** [comment]
on a similar vein:
1. import wallet using public key/address (Watch Only)
2. later, user decides to import wallet using passphrase (Send/receive enabled)

When I tried the above, the watch only wallet persisted and did not notify me on the lack of change. I had to go back and remove the 1. Watch Only wallet first and carry on step 2. In between, it would be useful to have an alert like
>"Existing wallet is found. Please remove and import again using passphrase to enable Send function."

**Comment by air1one** [comment]
Hi, I picked up this issue, see my pull request.

**Comment by alexbarnsley** [comment]
@air1one I won't close this issue based on your PR. What this issue describes is a specific network check to see if the wallet being imported is a new wallet or not. E.g. show me a warning message if the wallet with the passphrase I entered has no transactions at all (or something similar to that). I'm happy with your PR, I think this issue is just a small addition to that in order to help users make sure they're importing the correct wallets.

**Comment by air1one** [comment]
Ok I understand @alexbarnsley . I'll see what I can do to fully solve this issue.
