### ISSUE TITLE
Can't re-synchronize transactions and delegate list after network downtime

### ISSUE THREAD

**Issue by MoeB712** [ArkEcosystem/mobile-wallet#201]
After the network downtime about 4 days ago, my Android ARK mobile wallet can no longer re-synchronize. Transaction list stuck and it cannot fetch the delegate list (screenshot below). I've also tried to change peers which I was able to, but that did not help (screenshot below as well). Note that I've tried this using mobile data as well as WiFi so signal is not an issue here.

I heard network forked because it could not find consensus 4 days ago. Could it be that my app is connected (or trying to) to one of the forked chains?

Reference: https://www.reddit.com/r/ArkEcosystem/comments/9j0xrb/network_post_mortem_a_summary_of_the_recent/

Android Version: 8.0.0
ARK Mobile Wallet Version: 1.2.0

![screenshot_20180928-083631_ark_mobile](https://user-images.githubusercontent.com/26547563/46211255-189b1380-c301-11e8-8b00-eb33cb64cc68.jpg)
![screenshot_20180928-092435_ark mobile](https://user-images.githubusercontent.com/26547563/46211256-189b1380-c301-11e8-933a-0ad94e0eb5d0.jpg)

**Comment by Bjarzyna** [comment]
I was having very simillar problem for a few hours yesterday evening. Wallet was not syncing transactions or getting delegates list. I was stuck with peer 35.190.178.189 on a fixed height 5882485 for the entire time and changing peer did not work at all. Market data was updating smoothly so there was likely no problem with internet connection. Today it's all good but it sucks to have your wallet stuck while you're waiting for a transaction.
Wallet version 1.2.0, Android 5.1

**Comment by luciorubeens** [comment]
Hey @MoeB712, looks like some peers did not sync again and api does not respond. When you click to `change peer`, does it change or remain the same?

**Comment by MoeB712** [comment]
Hi @luciorubeens,
I've tried changing peers about 3 times yesterday and it successfully changed. However, now it doesnt. It gets stuck on "Looking for a good peer".
I was using mobile data yesterday and now I'm on wifi if that makes a difference.

Thanks.
