### ISSUE TITLE
Stuck with a peer, data not updating

### ISSUE THREAD

**Issue by Bjarzyna** [ArkEcosystem/mobile-wallet#202]
For a few hours yesterday evening my wallet was not syncing transactions or getting delegates list. I was stuck with peer 35.190.178.189 on a fixed height 5882485 for the entire time (delay 6-150, status OK) and changing peer did not work at all with message "looking for a good peer" and no followup. Market data was updating smoothly so there was likely no problem with internet connection. Today it's all good again, it fixed on itself.
If my math is correct and current block is 5921948 then I could've been stuck on this height for almost 4 days (5921948 - 5882485 * 8 / 60 / 60 / 24) without knowing about it. I was only able to spot it because I was waiting for a transaction. 
Wallet version 1.2.0, Android 5.1

**Comment by luciorubeens** [comment]
Hello @Bjarzyna, thanks for reporting. Glad it's already fixed!

is the same thing pointed out in #201.
