### ISSUE TITLE
Incorrect balances after v2 migration

### ISSUE THREAD

**Issue by vulet** [ArkEcosystem/mobile-wallet#234]
**Describe the bug**
"Hi guys, got a bug, so I assume: I just now updated the android wallet app, wallet balances are not being updated in the home screen, but when you open a wallet to see all transactions for the address it does show the up-to-date balance. Tapping back again, the same incorrect balance is shown again. In the app store description it states that the update works with v1 as well as v2, so I assume I have the most recent update installed." -TwerkingGorilla 

**To Reproduce**
1. Open wallet
2. Balance isn't updated
3. Change peer
4. Still isn't updated.

**Expected behavior**
Show the correct balance.

**Comment by luciorubeens** [comment]
Sorry my late reply, we released a new version improving compatibility with v2 last week.
