### ISSUE TITLE
Qr Scan imports devnet delegates 

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/mobile-wallet#262]
**Describe the bug**

I had the mobile wallet version installed on my android. I imported my wallet by scanning the qr code on my tv, (connected to my desktop) and it the wallet. 

Afterwards, I clicked delegates, (i'm on mainnet) on mobile. And it's showing devnet delegates?? 
Now....... I clicked convert to full wallet > scanned qr code again. Now no delegates are listing at all. 

**Wow!!! That dark mode is Beautiful!!!!*

**To Reproduce**
1. Download Mobile Wallet (Android Version
2. Create Pin
3. Import Wallet by scanning QR code off computer screen
4. Click delegates, and it's showing Devnet Delegates

**Expected behavior**
After scanning QR code, it should import my mainnet wallet. The wallet is there (listed) But has 0 Ark. On my desktop there is a balance of Ark showing.

**Comment by alexbarnsley** [comment]
Can I have screenshots of the list of profiles you have, of the wallets list, and of the "change peer" screen please. Thanks.

**Comment by alexbarnsley** [comment]
feel free to DM them if you feel they are sensitive in any way

**Comment by michaelthecryptoguy** [comment]
Screenshots have been sent

**Comment by alexbarnsley** [comment]
Thanks. It looks like your mainnet profile is connected to a devnet peer. Any ideas @luciorubeens? I've not seen this before 🤔
