### ISSUE TITLE
Pin code "self-destruct" after x amount of incorrect entries

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/mobile-wallet#263]
**Is your feature request related to a problem? Please describe.**
Currently it's possible that if someone gets ahold of a device with the mobile app (and has gotten past the phone lock screen - if there is one), there's no limit to the amount of attempts a user can make. That being said, there is throttling in place that prevents a user from entering a pin for 30 seconds after 3 consecutive failed attempts

**Describe the solution you'd like**
After 10 consecutive failed attempts (regardless of restarting the app), clear the entire database for the app.

**Comment by doubled1c3** [comment]
Upon initial install of mobile app, one of the welcome slides should mention what will happen if "you or someone else" enters too many wrong PIN attempts, further highlighting the need to back up passphrases
