### ISSUE TITLE
Build support with XCode 10.2 and Swift 4

### ISSUE THREAD

**Issue by luciorubeens** [ArkEcosystem/mobile-wallet#303]
**Describe the bug**

After upgrading XCode to version 10.2, I get an incompatible Swift version error.

**Additional context**

I tried to update `cordova-plugin-add-swift-support` and `cordova-ios`, but the library `cordova-plugin-qrscanner` throws compilation errors.

**Comment by vulet** [comment]
I can't build XCode, but do you think this is possibly related? https://github.com/bitpay/cordova-plugin-qrscanner/issues/238#issuecomment-478061794
